    version: "3.9"
    services:
      minecraft:
        build: .
        container_name: minecraft-server
        ports:
          - "25565:25565"
        restart: unless-stopped
        volumes:
          - ./server.properties:/server.properties
          - ./world:/world
